baseURL = "https://www.climbee.fun/"
relativeURLs = "True"
enableEmoji = true

defaultContentLanguage = 'hu'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false

[languages]
  [languages.hu]
    weight = 1
    title = "ClimBee –  Mászófalas Fejlesztő Központ Gyerekeknek | Budapest"
    languageName = "Magyar"
    copyright = "© ClimBee – Gyermekek Komplex Fejlesztését Támogató Alapítvány. Minden jog fenntartva."
  [languages.hu.params]
    description = "Belvárosi képességfejlesztő ház honlaplja."
  [languages.hu.params.footer.contact_form]
    header = "Kapcsolat"
  [languages.hu.params.footer.map]
    header = "Hol vagyunk"
  [languages.en]
    weight = 2
    title = "ClimBee Developmental Center"
    languageName = "English"
    copyright = "© ClimBee Developmental Center. All rights reserved."
  [languages.en.params]
    description = "Developmental Center with climbing in focus"
  [languages.en.params.footer.contact_form]
    header = "Contact"
  [languages.en.params.footer.map]
    header = "Our Location"

[HTTPCache]
  [HTTPCache.cache]
    [HTTPCache.cache.for]
      excludes = ['**']
      includes = []

[deployment]
  confirm = false
  dryRun = false
  force = false
  invalidateCDN = true
  maxDeletes = 256
  target = ''
  workers = 10
  [[deployment.targets]]
    name = 'production'
    url = 's3://climbee.fun?region=eu-north-1'

#  Compress and cache static assets for 1 week.
[[deployment.matchers]]
pattern = "^.+\\.(css|eot|html|ico|js|json|otf|svg|ttf|xml)$"
cacheControl = "max-age=604800, no-transform, public"
gzip = true

#  Cache static assets for 1 week, compression not required.
[[deployment.matchers]]
pattern = "^.+\\.(gif|jpg|jpeg|png|woff|woff2)$"
cacheControl = "max-age=604800, no-transform, public"
gzip = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
    tag = "tags"

[permalinks]
  therapistdetails = "/therapistdetails/:slug/"

[params]
    images = ['images/bee_vector_sqr.png']
    show_post_dates = false
    enableSourceMaps = true

    [[params.social]]
        title = "Instagram"
        icon = "fa-instagram"
        url = "https://www.instagram.com/climbeee"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "https://www.facebook.com/climbeee"
    [[params.social]]
        title = "Youtube"
        icon = "fa-youtube"
        url = "https://www.youtube.com/@ClimBee-fun"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"

    [params.footer.contact_form]
        enabled = true

    [params.footer.map]
        enabled = true
