baseURL = "https://example.org/"
languageCode = "en-us"
title = "Arcana for Hugo"

copyright = "© Untitled. All rights reserved"

[taxonomies]
    tag = "tags"

[params]
    description = "A business/corporate style responsive site template."
    images = ['images/metaimage.jpg']
    show_post_dates = false

    enableSourceMaps = true


    [[params.social]]
        title = "Instagram"
        icon = "fa-instagram"
        url = "#"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "#"
    [[params.social]]
        title = "Youtube"
        icon = "fa-youtube"
        url = "#"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"

    [params.footer]

        [[params.footer.links]]
            header = "Egyeb Tartalom"
        [[params.footer.links.links]]
            title = "Tapasztalatok"
            url = "#"
        [[params.footer.links.links]]
            title = "Engedelyek"
            url = "#"
        [[params.footer.links.links]]
            title = ""
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan dolor"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis rutrum accumsan"
            url = "#"

    [params.footer.contact_form]
        enabled = true
        header = "Irj Nekunk"
        action = ""
